language: python

python:
  - '3.9'

install:
  - pip3 install HookTest

script: hooktest ./ --scheme epidoc --workers 3 --verbose 5 --manifest --countword --console table --hookUI "http://ci.perseids.org/api/hook/v2.0/user/repositories/OpenGreekAndLatin/csel-dev"

before_deploy:
  - hooktest-build --travis --txt ./
  - results=$(cat manifest.txt)
  - DATE=`date +%Y-%m-%d`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
  - git add -A
  - git commit -m "Removed failing files" -m "Release $GIT_TAG"
  - git tag $GIT_TAG -a -m "$DATE" -m "PASSING FILES" -m "$results"
  - git push -q https://$GITPERM@github.com/OpenGreekAndLatin/csel-dev --tags

deploy:
  provider: releases
  api_key: $GITPERM
  skip_cleanup: true
  on:
    repo: OpenGreekAndLatin/csel-dev
    branch: master

env:
  global:
    major_version: 1
    minor_version: 1
