title: The First 1000 Years of Greek
description: XML files for the works in the First Thousand Years of Greek Project
google_analytics: 
show_downloads: true
theme: jekyll-theme-dinky

gems:
  - jekyll-mentions
