title: Csel-dev
description: "Corpus Scriptorum Ecclesiasticorum Latinorum: a machine-corrected EpiDoc version of the public domain volumes of the monumental collection of Latin Church Fathers. "
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
